title: ninioArtillero
description: >
  Hocus Pocus y KameHameHas.
  Encuentros con chilacayotas cósmicas y piratas truchas.
author: Xavier Góngora
email: "xaviergongora.contacto@gmail.com"
tagline: Xavier Gongora's personal blog
locale: en_US

theme: minima

# Runtime gem dependencies of minima
#
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social profiles
# SEO-tag
social:
  name: Xavier Góngora
  links:
    - https://soundcloud.com/ninioartillero
    - https://github.com/ninioArtillero
    - https://qoto.org/@xavigo
    - https://www.instagram.com/ninioartillero

#
# Theme-specific settings
#

# Social links
#
github_username:  ninioArtillero
instagram_username: ninioArtillero
rss: rss

mastodon:
 - username: xg
   instance: toplap.org

minima:
  skin: auto
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  date_format: "%Y-%m-%d"

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
  - activities.md
  - music.md
  - teaching.md
  - publications.md
  - archive.md
  - about.md

# Set to `true` to show excerpts on the homepage.
#
show_excerpts: true

defaults:
  - scope:
      path: "assets/pub/proceedings"
    values:
      proceedings: true
  -scope:
      path: "assets/pub/chapters"
    values:
      chapter: true
