title: ninioArtillero
description: >
  Hocus Pocus y KameHameHas.
  Encuentros con chilacayotas cósmicas y piratas truchas.
author: Xavier Góngora
email: "xaviergongora.contacto@gmail.com"

theme: minima

# Runtime gem dependencies of minima
#
plugins:
  - jekyll-feed
  - jekyll-seo-tag

#
# Theme-specific settings
#

# Social links
#
github_username:  ninioArtillero
instagram_username: ninioArtillero

mastodon:
 - username: xavigo
   instance: qoto.org

minima:
  skin: auto
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  date_format: "%Y-%m-%d"

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
# header_pages:
#   - about.md

# Set to `true` to show excerpts on the homepage.
#
show_excerpts: true
